exclude: (^tests|docs|examples)
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
      - id: ruff-format
        stages: [ commit ]
      - id: ruff
        args: [ --fix ]
        stages: [ commit ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies: [ types-PyYAML ]
        args: [--python-version=3.10, --ignore-missing-imports]
