site_name: pythogen
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  plugins:
    - search
  features:
    # - navigation.tabs
    - navigation.sections
    - search.suggest
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

repo_url: https://github.com/artsmolin/pythogen
repo_name: artsmolin/pythogen

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences